version: "4"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=docx_converter
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
